apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    alicloud-pvname: pgp-container
  name: pgp-container
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  flexVolume:
    driver: alicloud/oss
    options:
      akId: [key]
      akSecret: [secret]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: oss