apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world
    image: registry-intl-vpc.eu-central-1.aliyuncs.com/test-hao/test:latest
  imagePullSecrets:
  - name: regcred