apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world
    image: registry-intl.eu-central-1.aliyuncs.com/[namespace]/[repo]:[tag]
  imagePullSecrets:
  - name: regcred