apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgp-demo-oss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      alicloud-pvname: pgp-demo-oss
  storageClassName: oss
  volumeName: pgp-demo-oss
